export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_ROBOT_START = "REQUEST_ROBOT_START";
export const REQUEST_ROBOT_SUCCESS = "REQUEST_ROBOT_SUCCESS";
export const REQUEST_ROBOT_FAIL = "REQUEST_ROBOT_FAIL";